routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\AuthController as AdminAuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\StreamController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductWishlistController;
use App\Http\Controllers\SellerMoneyRequestController;





/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home'])->name('layouts.welcome');
Route::get('account', [AccountController::class, 'index'])->name('account.index');
Route::get('contact', [HomeController::class, 'contact'])->name('contact.index');
Route::get('/products/all', [App\Http\Controllers\ProductController::class, 'index'])->name('product.index');
Route::get('/products/{products}',  [ProductController::class,'show'])->name('product.show');

Route::post('order', [OrderController::class, 'store'])->name('order.store');
Route::get('/favorites', [ProductWishlistController::class, 'index'])->name('favorite.index');

Route::get('/s/{uuid}', [StreamController::class, 'show'])->name('stream.show');

Route::middleware('auth')->group(function(){

    Route::get('/product-wishlist', [ProductWishlistController::class,'index'])->name('wishlist.index');
    Route::post('/product-wishlist/{product_id}', [ProductWishlistController::class,'store']);
    Route::delete('/product-wishlist/{product_id}', [ProductWishlistController::class,'destroy']);

    Route::get('/my-orders', [OrderController::class, 'myOrders'])->name('customer.orders');

    // Route::middleware(['role|customer'])->group(function(){
    // });
});

Route::prefix('admin')->group(function () {

    Route::get('/login', [AdminAuthController::class, 'loginShow']);
    Route::post('/login', [AdminAuthController::class, 'login'])->name('admin.login');
    Route::post('/dashboard', [DashboardController::class, 'welcome'])->name('admin.dashboard');

    Route::middleware('auth')->group(function () {

        Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'categories'])->name('admin.categories.index');
        Route::get('/products', [App\Http\Controllers\ProductController::class, 'product'])->name('admin.product.index');
        Route::get('/offers',  [OfferController::class,'index'])->name('admin.offer.index');
        Route::get('/offers/{offer_id}',  [OfferController::class,'show'])->name('admin.offer.show');

        Route::get('/orders',  [OrderController::class,'index'])->name('admin.orders.index');
        Route::get('/orders/{order_id}',  [OrderController::class,'show'])->name('admin.orders.show');

        Route::post('/orders/{order_id}',  [OrderController::class,'update'])->name('admin.orders.update');

        Route::get('/streams', [StreamController::class, 'index'])->name('stream.index');


        Route::resource('categories', CategoryController::class);
        Route::resource('products', AdminProductController::class)->except([
            'show'
        ]);

        Route::post('/stream', [StreamController::class,'store']);

        // Route::post('logout', [AdminAuthController::class, 'logout'])->name('logout');
        Route::prefix('dashboard')->group(function () {
            Route::get('/', [DashboardController::class, 'welcome']);
        });

        Route::get('/seller-money-requests',  [SellerMoneyRequestController::class,'index'])->name('admin.money-requests.index');

        Route::get('/money-requests/create',  [SellerMoneyRequestController::class,'create'])->name('admin.money-requests.create');
        Route::post('/money-requests',  [SellerMoneyRequestController::class,'store'])->name('admin.money-requests.store');
        Route::get('/money-requests/change-status/{request_id}/{status}',  [SellerMoneyRequestController::class,'changeStatus'])->name('admin.money-requests.change-status');

    });
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Product extends Model
{
    use HasFactory, Mediable;

    protected $fillable = [
        'category_id',
        'name',
        'description',
        'image',
        'price',
        'profit',
        'is_published',
        'advertising_link',
        'coin'
        // 'customers_show_count'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getImageAttribute($value)
    {
        return ($value) ? (gettype($value) != 'string' ) ? stream_get_contents($value) : $value     : '';
    }

    public function scopeActive($query)
    {
        return $query->where('is_published', true);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Products\StoreProduct;
use App\Http\Requests\Products\UpdateProduct;

use App\Repositories\Admin\ProductRepository;

use App\Models\Product;
use App\Models\Category;


class ProductController extends Controller
{

    protected $repo;

    public function __construct(ProductRepository $repo)
    {
        $this->repo = $repo;
    }

    public function index(Request $request)
    {
        $input = $request->validate([
            'category_id' => 'nullable|exists:categories,id',
            'product_name' => 'nullable',
            'order_by' => 'nullable'
        ]);

        $query = Product::query();

        if(isset($input['category_id'])){
            $query = $query->where('category_id', $input['category_id']);
        }

        if(isset($input['product_name'])){
            $query = $query->where('name','ilike', '%'.$input['product_name'].'%');
        }

        if(isset($input['order_by'])){
            $query = $query->orderBy($input['order_by']);
        }else{
            $query = $query->orderByDesc('created_at');
        }

        $products = $query->get();

        return view('admin.product.index', compact('products'));

    }

    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', [
            'categories' => $categories
        ]);
    }

    public function store(StoreProduct $request)
    {

        $this->repo->store($request->all());


        return redirect()->route('products.index');
    }

    public function show($id)
    {
        // $item = $this->repo->findById($id);
        $product = Product::findOrFail($id);

        $similar_products = [];

        if($product){
            $similar_products = Product::where('category_id', $product->category_id)->where('id','!=', $product->id)->get();
        }

        return view('product.show', [
            'products' => $product,
            'similar_products' => $similar_products
        ]);
    }

    public function edit($id)
    {
        $product = $this->repo->findById($id);
        $categories = Category::all();

        return view('admin.product.edit', compact('product', 'categories'));
    }

    public function update(UpdateProduct $request, $id)
    {
        $this->repo->update($request->all(), $id);
        return redirect()->route('products.index');
    }

    public function destroy($id)
    {
        Product::where('id', $id)->delete();
        return redirect()->route('products.index')
                        ->with('success','list deleted successfully');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Product;
use App\Models\Category;
use App\Models\Region;



class ProductController extends Controller
{
    public function index(Request $request)
    {
        $categories = Category::all();

        $input = $request->validate([
            'category_id' => 'nullable|exists:categories,id',
            'product_name' => 'nullable',
            'order_by' => 'nullable'
        ]);

        $query = Product::query();

        if(isset($input['category_id'])){
            $query = $query->where('category_id', $input['category_id']);
        }

        if(isset($input['product_name'])){
            $query = $query->where('name','ilike', '%'.$input['product_name'].'%');
        }

        if(isset($input['order_by'])){
            $query = $query->orderBy($input['order_by']);
        }else{
            $query = $query->orderByDesc('created_at');
        }

        $products = $query->where('is_published', true)->get();

        return view('product.index', compact('products', 'categories'));
    }

    public function show($id)
    {
        // $item = $this->repo->findById($id);
        $product = Product::findOrFail($id);
        $regions = Region::get();
        $similar_products = [];

        if($product){
            $similar_products = Product::where('category_id', $product->category_id)->where('id','!=', $product->id)->get();
        }

        return view('product.show', [
            'products' => $product,
            'similar_products' => $similar_products,
            'regions' => $regions
        ]);
    }


}

resources/views/admin/product/create.blade.php
@extends('layouts.admin')

@section('title', 'Product')

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="card-header">
            <h4>Mahsulot qo'shish</h4>
        </div>
        <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data" class="card-body">
            @csrf()
                <div class="mb-3">
                    <label for="exampleDataList" class="form-label">Mahsulot kategoriyasi</label>
                    <select class="form-select" id="inputGroupSelect01" name="category_id">
                        <option value="">Kategoriyani tanlang...</option>
                        @foreach($categories as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @endforeach
                    </select>
                </div>
                <span class="text-danger">{{ $errors->first('category_id') }}</span>
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label" for="basic-default-name">Mahsulot nomi</label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="name" id="basic-default-name"  @error('name') is-invalid @else is-valid @enderror" placeholder="Mahsulot nomini shu yerga kiriting" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('name') }}</span>
                <div>
                    <label for="exampleFormControlTextarea1" class="form-label">Mahsulot haqida batafsil ma'lumot</label>
                    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" @error('description') is-invalid @else is-valid @enderror"></textarea>
                </div>
                <span class="text-danger">{{ $errors->first('description') }}</span>
                <div class="mb-3 mt-3">
                    <label for="formFileMultiple" class="form-label">Mahsulot rasmi</label>
                    <input class="form-control" type="file" name="image" id="formFileMultiple" multiple @error('image') is-invalid @else is-valid @enderror" />
                </div>
                <span class="text-danger">{{ $errors->first('image') }}</span>
                <div class="mb-3">
                    <label for="html5-number-input" class="col-md-2 col-form-label">Narxi</label>
                    <div class="col-md-12">
                      <input class="form-control" type="number" name="price" placeholder="450000" id="html5-number-input" @error('price') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('price') }}</span>
                <div class="mb-3">
                    <label for="html5-number-input" class="col-md-2 col-form-label">Profit</label>
                    <div class="col-md-12">
                      <input class="form-control" type="number" name="profit" placeholder="30000" id="html5-number-input" @error('profit') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('advertising_link') }}</span>
                <div class="mb-3">
                    <label for="advertising_link" class="form-label">Reklama posti uchun link</label>
                    <div class="col-md-12">
                        <input class="form-control" type="text" name="advertising_link" placeholder="Telegramdan olingan linkni kiriting" id="advertising_link" @error('advertising_link') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('coin') }}</span>
                <div class="mb-3">
                    <label for="coin" class="form-label">Mahsulot uchun COIN miqdorini kiriting</label>
                    <div class="col-md-12">
                        <input class="form-control" type="number" min="0" name="coin" placeholder="COIN miqdorini kiriting" id="coin" @error('coin') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('profit') }}</span>
                <div class="mb-3">
                    <label for="exampleDataList" class="form-label">Mahsulot holati</label>
                    <select class="form-select" id="inputGroupSelect01" name="is_published">
                        <option value="">Tanlang...</option>
                        <option value="1">Faol</option>
                        <option value="0">Faol emas</option>
                      </select>
                </div>
                <button type="submit" class="btn btn-primary btn-md" style="float: right">
                    <i class="menu-icon tf-icons bx bx-check"></i>
                    {{ __('Ma\'lumotni saqlash') }}
                </button>
        </form>
    </div>

</div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    });

</script>
@stop

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')

@section('title', 'Product')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="card">
            <div class="card-header">
                <h4>Mahsulotni tahrirlash</h4>
            </div>
            <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data"
                class="card-body">
                @csrf()
                @method('PUT')
                <div class="mb-3">
                    <label for="exampleDataList" class="form-label">Mahsulot kategoriyasi</label>
                    <select class="form-select" id="inputGroupSelect01"  name="category_id">
                        @foreach($categories as $item)
                            @if($item->id == $product->category_id)
                            <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                            @else
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <span class="text-danger">{{ $errors->first('category_id') }}</span>
                <div class="mb-3">
                    <label class="col-sm-1 col-form-label" for="basic-default-name">Mahsulot nomi</label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="name" value="{{ $product->name }}" id="basic-default-name"
                            @error('name') is-invalid @else is-valid @enderror" placeholder="Category Name" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('name') }}</span>
                <div>
                    <label for="exampleFormControlTextarea1" class="form-label">Mahsulot haqida batafsil ma'lumot</label>
                    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"
                        @error('description') is-invalid @else is-valid @enderror">{{ $product->description }}</textarea>
                </div>
                <span class="text-danger">{{ $errors->first('name') }}</span>
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label">Mahsulot rasmi</label>
                    <input class="form-control" type="file" name="image" value="{{ $product->image }}" id="formFileMultiple" multiple
                        @error('image') is-invalid @else is-valid @enderror" />
                </div>
                <span class="text-danger">{{ $errors->first('image') }}</span>
                <div class="mb-3">
                    <label for="html5-number-input" class="col-md-2 col-form-label">Narxi</label>
                    <div class="col-md-12">
                        <input class="form-control" type="text" name="price" value="{{ $product->price }}" placeholder="123456.."
                            id="html5-number-input" @error('price') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('price') }}</span>
                <div class="mb-3">
                    <label for="html5-number-input" class="col-md-2 col-form-label">Mahsulotdan olinadigan foyda</label>
                    <div class="col-md-12">
                        <input class="form-control" type="text" name="profit" value="{{ $product->profit }}"
                            id="html5-number-input" @error('profit') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('advertising_link') }}</span>
                <div class="mb-3">
                    <label for="advertising_link" class="form-label">Reklama posti uchun link</label>
                    <div class="col-md-12">
                        <input class="form-control" type="text" name="advertising_link" value="{{ $product->advertising_link }}" id="advertising_link" @error('advertising_link') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('coin') }}</span>
                <div class="mb-3">
                    <label for="coin" class="form-label">Mahsulot uchun COIN miqdorini kiriting</label>
                    <div class="col-md-12">
                        <input class="form-control" type="number" min="0" name="coin" value="{{ $product->coin }}"  id="coin" @error('coin') is-invalid @else is-valid @enderror" />
                    </div>
                </div>
                <span class="text-danger">{{ $errors->first('is_published') }}</span>
                <div class="mb-3">
                    <label for="exampleDataList" class="form-label">Mahsulot holati</label>
                    <select class="form-select" id="inputGroupSelect01" name="is_published">
                        <option value="">Tanlang...</option>
                        <option value="1" {!! $product->is_published ? ' selected="selected"' : ''!!}>Faol</option>
                        <option value="0" {!! !$product->is_published ? ' selected="selected"' : ''!!}>Faol emas</option>
                      </select>
                </div>
                <button type="submit" class="btn btn-primary btn-md" style="float: right !important;">
                    <i class="menu-icon tf-icons bx bx-check"></i>
                    {{ __('Ma\'lumotni saqlash') }}
                </button>
            </form>
        </div>
    </div>
@stop
@section('js')
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        });
    </script>
@stop

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('title', 'Product')

@section('content_header')
<h4>Product</h4>
@stop

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-lists-center">
            <h4>Mahsulotlar ro'yxati</h4>
            <h3 class="card-title d-flex">
                <a href="{{ route('products.create') }}" class="btn btn-primary" style="float: right"><span class="menu-icon tf-icons bx bx-plus"></span>Mahsulot qo'shish
                </a>
            </h3>
        </div>
        <div class="card-body">
            <div class="">
                <table cellpadding="0" cellspacing="0" id="example" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>№</th>
                            <th>Mahsulot kategoriyasi</th>
                            <th>Mahsulot nomi</th>
                            <th>Mahsulot rasmi</th>
                            <th>Narxi</th>
                            <th>Adminlar uchun foyda</th>
                            <th>Mahsulot holati</th>
                            <th>Amallar</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php $i = 1;?>
                        @foreach($products as $item)
                        <tr style="height: 150px !important;">
                            <td>{{ $i++ }}</td>
                            <td>{{ $item->category->name }} </td>
                            <td>{{ $item->name }} </td>
                            <td><img src="{{ $item->image }}" alt=""style="width:120px; height: 80px"></td>
                            <td>{{ number_format($item->price, 0, ' ', ' ' ) }} so'm</td>
                            <td>{{ number_format($item->profit, 0, ' ', ' ') }} so'm</td>
                            <td>{{ ($item->is_published) ? 'Faol' : 'Faol emas' }} </td>
                            <td class="d-flex flex-wrap" style="align-items: center; height: 100%;">
                                <a href="{{ route('products.edit',  $item->id) }}" class="btn btn-info btn-sm mb-2" style="margin-right: 20px; width: 100px;">
                                    <i class="menu-icon tf-icons bx bx-edit-alt"></i>
                                    <span class="">Tahrirlash</span>
                                </a>
                                {{-- <form action="{{ route('products.destroy',  $item->id) }}" method="post" onsubmit="return confirm('Сиз ростдан ҳам ушбу маълумотни ўчиришни хохлайсизми ?')">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger" style="width: 100px">
                                        <i class="menu-icon tf-icons bx bx-trash"></i>
                                        <span class="">O'chirish</span>
                                    </button>
                                </form> --}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{-- {{ $products->links() }} --}}
</div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    });

</script>
@stop

resources/views/admin/product/show.blade.php
@extends('layouts.admin')

@section('content')

@endsection