routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\AuthController as AdminAuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\StreamController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductWishlistController;
use App\Http\Controllers\SellerMoneyRequestController;





/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home'])->name('layouts.welcome');
Route::get('account', [AccountController::class, 'index'])->name('account.index');
Route::get('contact', [HomeController::class, 'contact'])->name('contact.index');
Route::get('/products/all', [App\Http\Controllers\ProductController::class, 'index'])->name('product.index');
Route::get('/products/{products}',  [ProductController::class,'show'])->name('product.show');

Route::post('order', [OrderController::class, 'store'])->name('order.store');
Route::get('/favorites', [ProductWishlistController::class, 'index'])->name('favorite.index');

Route::get('/s/{uuid}', [StreamController::class, 'show'])->name('stream.show');

Route::middleware('auth')->group(function(){

    Route::get('/product-wishlist', [ProductWishlistController::class,'index'])->name('wishlist.index');
    Route::post('/product-wishlist/{product_id}', [ProductWishlistController::class,'store']);
    Route::delete('/product-wishlist/{product_id}', [ProductWishlistController::class,'destroy']);

    Route::get('/my-orders', [OrderController::class, 'myOrders'])->name('customer.orders');

    // Route::middleware(['role|customer'])->group(function(){
    // });
});

Route::prefix('admin')->group(function () {

    Route::get('/login', [AdminAuthController::class, 'loginShow']);
    Route::post('/login', [AdminAuthController::class, 'login'])->name('admin.login');
    Route::post('/dashboard', [DashboardController::class, 'welcome'])->name('admin.dashboard');

    Route::middleware('auth')->group(function () {

        Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'categories'])->name('admin.categories.index');
        Route::get('/products', [App\Http\Controllers\ProductController::class, 'product'])->name('admin.product.index');
        Route::get('/offers',  [OfferController::class,'index'])->name('admin.offer.index');
        Route::get('/offers/{offer_id}',  [OfferController::class,'show'])->name('admin.offer.show');

        Route::get('/orders',  [OrderController::class,'index'])->name('admin.orders.index');
        Route::get('/orders/{order_id}',  [OrderController::class,'show'])->name('admin.orders.show');

        Route::post('/orders/{order_id}',  [OrderController::class,'update'])->name('admin.orders.update');

        Route::get('/streams', [StreamController::class, 'index'])->name('stream.index');


        Route::resource('categories', CategoryController::class);
        Route::resource('products', AdminProductController::class)->except([
            'show'
        ]);

        Route::post('/stream', [StreamController::class,'store']);

        // Route::post('logout', [AdminAuthController::class, 'logout'])->name('logout');
        Route::prefix('dashboard')->group(function () {
            Route::get('/', [DashboardController::class, 'welcome']);
        });

        Route::get('/seller-money-requests',  [SellerMoneyRequestController::class,'index'])->name('admin.money-requests.index');

        Route::get('/money-requests/create',  [SellerMoneyRequestController::class,'create'])->name('admin.money-requests.create');
        Route::post('/money-requests',  [SellerMoneyRequestController::class,'store'])->name('admin.money-requests.store');
        Route::get('/money-requests/change-status/{request_id}/{status}',  [SellerMoneyRequestController::class,'changeStatus'])->name('admin.money-requests.change-status');

    });
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Category extends Model
{
    use HasFactory;
    use Mediable;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'image'
    ];

    public function getImageAttribute($value)
    {
        return ($value) ? (gettype($value) != 'string' ) ? stream_get_contents($value) : $value     : '';
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\Category\StoreCategory;
use App\Http\Requests\Category\UpdateCategory;

use App\Repositories\Admin\CategoryRepository;

use App\Models\Category;

class CategoryController extends Controller
{

    protected $repo;

    public function __construct(CategoryRepository $repo)
    {
        $this->repo = $repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->repo->all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategory $request)
    {
        $this->repo->store($request->all());
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = $this->categories->findById($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->repo->findById($id);
        return view('admin.categories.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategory $request, $id)
    {
        $this->repo->update($request->all(), $id);
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::where('id', $id)->delete();
        return redirect()->route('categories.index')
                        ->with('success','Item deleted successfully');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Category;

class CategoryController extends Controller
{
    public function categorie(){

        $categories = Category::orderByDesc('created_at')->paginate(20);

        return view('admin.categories.index', compact('categories'));

    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', 'Category')

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="card-header">
            <h4>Kategoriya yaratish</h4>
        </div>
        <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data" class="card-body">
            @csrf()
                <div class="mb-3">
                    <label class="col-sm-3 col-form-label" for="basic-default-name">Kategoriya nomi</label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="name" id="basic-default-name"  @error('name') is-invalid @else is-valid @enderror" placeholder="Kategoriya nomi" />
                    </div>
                </div>
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label">Kategoriya rasmi</label>
                    <input class="form-control @error('image') is-invalid @else is-valid @enderror" type="file" name="image" id="image">
                </div>
                <span class="text-danger">{{ $errors->first('image') }}</span>

            <button type="submit" class="btn btn-primary btn-md btn-xl btn-sm" style="float: right">
                <i class="menu-icon tf-icons bx bx-check"></i>
                {{ __('Ma\'lumotni saqlash') }}
            </button>
        </form>
    </div>
    {{-- {{ $categories->links() }} --}}
</div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    });

</script>
@stop

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', 'Category')

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="card-header">
            <h4>Kategoriyani tahrirlash</h4>
        </div>
        <form action="{{ route('categories.update', $item[0]->id) }}" method="POST" enctype="multipart/form-data" class="card-body">
            @csrf()
            @method('PUT')
                <div class="row mb-3">
                    <label class="col-sm-1 col-form-label" for="basic-default-name">Kategoriya nomi</label>
                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="name" value="{{ $item[0]->name }}" id="basic-default-name"  @error('name') is-invalid @else is-valid @enderror" placeholder="Category Name" />
                    </div>
                </div>
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label">Kategoriya rasmi</label>
                    <input class="form-control" type="file" name="image" value="{{ $item[0]->image }}" id="formFileMultiple" multiple @error('image') is-invalid @else is-valid @enderror" />
                </div>
                <span class="text-danger">{{ $errors->first('name') }}</span>

            <button type="submit" class="btn btn-primary btn-md" style="float: right !important;">
                <i class="menu-icon tf-icons bx bx-check"></i>
                {{ __('Ma\'lumotni saqlash') }}
            </button>
        </form>
    </div>
</div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    });

</script>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title', 'Category')

@section('content_header')
<h4>Category</h4>
@stop

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h4>Kategoriyalar ro'yxati</h4>
            <h3 class="card-title d-flex">
                <a href="{{ route('categories.create') }}" class="btn btn-primary" style="float: right"><span class="menu-icon tf-icons bx bx-plus"></span>Ma'lumot qo'shish
                </a>
            </h3>
        </div>



        <div class="card-body">
            <div class="">
                <table cellpadding="0" cellspacing="0" id="example" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>№</th>
                            <th>Kategoriya nomi</th>
                            <th>Kategoriya rasmi</th>
                            <th>Amallar</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php $i = 1;?>
                        @foreach($categories as $item)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $item->name }} </td>
                            <td><img src="{{ $item->image }}" style="width:120px; height: 80px"></td>
                            <td class="d-flex">
                                <a href="{{ route('categories.edit',  $item->id) }}" class="btn btn-info btn-sm" style="margin-right: 20px">
                                    <i class="menu-icon tf-icons bx bx-edit-alt"></i>
                                    <span class="">Tahrirlash</span>
                                </a>
                                <form action="{{ route('categories.destroy',  $item->id) }}" method="post" onsubmit="return confirm('Сиз ростдан ҳам ушбу маълумотни ўчиришни хохлайсизми ?')">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        <i class="menu-icon tf-icons bx bx-trash"></i>
                                        <span class="">O'chirish</span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{ $categories->links() }}
</div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    });

</script>
@stop